#!/bin/zsh
mydir=${0:a:h}
cd $mydir
echo $mydir
cd appero


# Check for installed file
if [ ! -f .installed ]; then
    echo "Installing appero..."
    # Install Homebrew
    if [ ! -f /opt/homebrew/bin/brew ]; then
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        echo "Homebrew already installed"
    fi
     
    if which node > /dev/null
    then
        echo "node is installed, skipping..."
    else
        echo "Installing node..."
        # Install Homebrew packages
        brew install node
    fi

    # Install npm packages
    echo "Installing npm packages..."
    npm install
    
    touch .installed
fi

echo "Starting appero..."

# Run
node appero.js

