#!/bin/zsh
mydir=${0:a:h}
cd $mydir
echo $mydir

# Check for installed file
if [ -f .installed ]; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # Install Homebrew packages
    brew install node

    # Install Yarn packages
    cd appero
    npm install
    
    touch .installed
fi

# Run
cd appero
node appero.js

